window.CODING_MENTOR_DATA = {
  definitions: {
    version: 1,
    groups: [
      {
        title: "Arrays / Strings / HashMap",
        items: [
          "dsa-two-sum",
          "dsa-best-time-buy-sell-stock",
          "dsa-contains-duplicate",
          "dsa-product-of-array-except-self",
          "dsa-maximum-subarray",
          "dsa-longest-palindromic-substring",
          "dsa-group-anagrams",
          "dsa-valid-anagram",
          "dsa-top-k-frequent-elements",
          "dsa-merge-intervals",
          "dsa-meeting-rooms",
          "dsa-trapping-rain-water",
          "dsa-next-permutation",
          "dsa-maximum-product-subarray",
          "dsa-string-to-integer-atoi",
          "dsa-valid-palindrome",
          "dsa-longest-common-prefix",
          "dsa-spiral-matrix",
          "dsa-first-missing-positive",
          "dsa-find-all-anagrams-in-a-string",
          "dsa-isomorphic-strings",
          "dsa-reverse-words-in-a-string",
          "dsa-median-of-two-sorted-arrays",
          "dsa-majority-element",
          "dsa-move-zeroes",
          "dsa-plus-one",
          "dsa-3sum",
          "dsa-subarray-sum-equals-k",
          "dsa-max-length-subarray-sum-divisible-by-k",
          "dsa-fraction-to-recurring-decimal",
          "dsa-valid-number",
        ],
      },
      {
        title: "Sliding Window / Two-Pointer",
        items: [
          "dsa-longest-substring-without-repeating-characters",
          "dsa-minimum-window-substring",
          "dsa-permutation-in-string",
          "dsa-longest-repeating-character-replacement",
          "dsa-minimum-size-subarray-sum",
          "dsa-container-with-most-water",
          "dsa-longest-continuous-subarray-abs-diff-limit",
        ],
      },
      {
        title: "Linked List",
        items: [
          "dsa-reverse-linked-list",
          "dsa-merge-two-sorted-lists",
          "dsa-detect-cycle-linked-list",
          "dsa-middle-of-linked-list",
          "dsa-remove-nth-node-from-end",
          "dsa-intersection-of-two-linked-lists",
          "dsa-add-two-numbers",
          "dsa-palindrome-linked-list",
          "dsa-swap-nodes-in-pairs",
          "dsa-copy-list-with-random-pointer",
          "dsa-flatten-multilevel-doubly-linked-list",
          "dsa-lru-cache-linked-list",
          "dsa-lfu-cache",
        ],
      },
      {
        title: "Trees / Graphs / BFS / DFS",
        items: [
          "dsa-max-depth-binary-tree",
          "dsa-validate-bst",
          "dsa-level-order-traversal",
          "dsa-invert-binary-tree",
          "dsa-diameter-of-binary-tree",
          "dsa-lowest-common-ancestor",
          "dsa-serialize-deserialize-binary-tree",
          "dsa-binary-tree-right-side-view",
          "dsa-count-good-nodes",
          "dsa-top-bottom-view-of-tree",
          "dsa-symmetric-tree",
          "dsa-construct-tree-preorder-inorder",
          "dsa-number-of-islands",
          "dsa-clone-graph",
          "dsa-course-schedule",
          "dsa-course-schedule-ii",
          "dsa-word-ladder",
          "dsa-graph-valid-tree",
          "dsa-pacific-atlantic-water-flow",
          "dsa-flood-fill",
          "dsa-rotten-oranges",
          "dsa-shortest-path-binary-matrix",
          "dsa-employee-importance",
          "dsa-all-nodes-distance-k",
          "dsa-trie-prefix-tree",
          "dsa-word-ladder-ii",
          "dsa-evaluate-division",
          "dsa-boundary-of-binary-tree",
        ],
      },
      {
        title: "Heaps / Stacks / Queues / Deque",
        items: [
          "dsa-kth-largest-element",
          "dsa-top-k-frequent-elements-heap",
          "dsa-sliding-window-maximum",
          "dsa-find-median-data-stream",
          "dsa-implement-stack-using-queues",
          "dsa-implement-queue-using-stacks",
          "dsa-min-stack",
          "dsa-largest-rectangle-histogram",
          "dsa-daily-temperatures",
          "dsa-valid-parentheses",
          "dsa-longest-valid-parentheses",
          "dsa-simplify-path",
          "dsa-next-greater-element",
        ],
      },
      {
        title: "Backtracking / Recursion",
        items: [
          "dsa-generate-parentheses",
          "dsa-subsets",
          "dsa-permutations",
          "dsa-combination-sum",
          "dsa-n-queens",
          "dsa-word-search",
          "dsa-word-search-ii",
          "dsa-sudoku-solver",
          "dsa-remove-invalid-parentheses",
          "dsa-partition-k-equal-sum-subsets",
        ],
      },
      {
        title: "Sorting / Searching / Binary Search",
        items: [
          "dsa-search-rotated-sorted-array",
          "dsa-find-peak-element",
          "dsa-koko-eating-bananas",
          "dsa-search-2d-matrix",
          "dsa-sort-colors",
          "dsa-count-smaller-numbers-after-self",
          "dsa-first-bad-version",
          "dsa-kth-smallest-sorted-matrix",
          "dsa-capacity-ship-packages",
          "dsa-find-min-rotated-sorted-array",
        ],
      },
      {
        title: "Dynamic Programming",
        items: [
          "dsa-climbing-stairs",
          "dsa-house-robber",
          "dsa-coin-change",
          "dsa-unique-paths",
          "dsa-longest-increasing-subsequence",
          "dsa-edit-distance",
          "dsa-word-break",
          "dsa-jump-game",
          "dsa-minimum-path-sum",
          "dsa-decode-ways",
          "dsa-partition-equal-subset-sum",
          "dsa-regular-expression-matching",
          "dsa-palindrome-partitioning",
          "dsa-distinct-subsequences",
          "dsa-longest-common-subsequence",
          "dsa-01-knapsack",
        ],
      },
      {
        title: "Greedy / Hashing / Bit Manipulation",
        items: [
          "dsa-candy",
          "dsa-gas-station",
          "dsa-assign-cookies",
          "dsa-partition-labels",
          "dsa-single-number",
          "dsa-number-of-1-bits",
          "dsa-counting-bits",
          "dsa-subarray-xor",
          "dsa-power-of-two-three-four",
          "dsa-missing-number",
          "dsa-hamming-distance",
          "dsa-reverse-bits",
          "dsa-find-duplicate-number",
        ],
      },
      {
        title: "LLD Problems",
        items: [
          "lld-parking-lot",
          "lld-vending-machine",
          "lld-elevator-system",
          "lld-logger-system",
          "lld-snake-ladder",
          "lld-chess-game",
          "lld-atm-machine",
          "lld-rate-limiter",
          "lld-url-shortener",
          "lld-splitwise",
          "lld-bookmyshow",
          "lld-restaurant-booking",
          "lld-email-service",
          "lld-cache-lru-lfu",
          "lld-message-queue",
          "lld-trie-prefix-search",
          "lld-library-management",
          "lld-food-delivery",
          "lld-ride-sharing",
          "lld-cricket-scoreboard",
          "lld-notification-system",
          "lld-leaderboard",
          "lld-traffic-light",
          "lld-file-system",
          "lld-task-scheduler",
          "lld-tinyurl",
          "lld-job-scheduler",
          "lld-hashmap-hashset",
          "lld-thread-safe-order-book",
          "lld-rw-lock-cache",
          "lld-blocking-queue-from-scratch",
          "lld-async-logger-ring-buffer",
          "lld-transaction-ledger",
          "lld-rule-engine",
          "lld-generic-connection-pool",
          "lld-hotel-flight-booking",
          "lld-redis-like-kv-store",
        ],
      },
      {
        title: "HLD Problems",
        items: [
          "hld-api-gateway",
          "hld-caching-system",
          "hld-cdn",
          "hld-chat-application",
          "hld-collaborative-editing-crdt",
          "hld-dashboard-metrics",
          "hld-distributed-cache",
          "hld-distributed-file-storage",
          "hld-distributed-job-scheduler",
          "hld-distributed-ledger",
          "hld-distributed-logging",
          "hld-distributed-rate-limiter",
          "hld-ecommerce-platform",
          "hld-eod-batch-engine",
          "hld-file-storage",
          "hld-flash-sale-checkout",
          "hld-food-delivery-app",
          "hld-fraud-aml-pipeline",
          "hld-iam-trading-desks",
          "hld-leaderboard-system",
          "hld-market-data-ingestion",
          "hld-message-broker-from-scratch",
          "hld-messaging-system",
          "hld-notification-queue",
          "hld-notification-system",
          "hld-payment-settlement-gateway",
          "hld-payment-system",
          "hld-payment-wallet",
          "hld-rate-limiter",
          "hld-realtime-analytics",
          "hld-realtime-trade-processing",
          "hld-recommendation-system",
          "hld-ride-sharing-app",
          "hld-risk-regulatory-reporting",
          "hld-saas-metering-billing",
          "hld-search-autocomplete",
          "hld-social-feed",
          "hld-stock-exchange",
          "hld-stock-ticker-leaderboard",
          "hld-ticket-booking-system",
          "hld-url-shortener",
          "hld-web-crawler",
        ],
      },
      {
        title: "CSES Introductory Problems",
        items: [
          "cses-weird-algorithm",
          "cses-missing-number",
          "cses-repetitions",
          "cses-increasing-array",
          "cses-permutations",
          "cses-number-spiral",
          "cses-two-knights",
          "cses-two-sets",
          "cses-bit-strings",
          "cses-coin-piles",
          "cses-creating-strings",
          "cses-apple-division",
        ],
      },
      {
        title: "CSES Sorting and Searching",
        items: [
          "cses-distinct-numbers",
          "cses-apartments",
          "cses-ferris-wheel",
          "cses-concert-tickets",
          "cses-restaurant-customers",
          "cses-movie-festival",
          "cses-sum-of-two-values",
          "cses-maximum-subarray-sum",
          "cses-stick-lengths",
          "cses-missing-coin-sum",
          "cses-collecting-numbers",
          "cses-playlist",
          "cses-towers",
          "cses-traffic-lights",
          "cses-subarray-sums-i",
        ],
      },
      {
        title: "CSES Dynamic Programming",
        items: [
          "cses-dice-combinations",
          "cses-minimizing-coins",
          "cses-coin-combinations-i",
          "cses-coin-combinations-ii",
          "cses-removing-digits",
          "cses-grid-paths-i",
          "cses-book-shop",
          "cses-array-description",
          "cses-edit-distance",
          "cses-rectangle-cutting",
          "cses-money-sums",
          "cses-projects",
        ],
      },
      {
        title: "CSES Graph Algorithms",
        items: [
          "cses-counting-rooms",
          "cses-labyrinth",
          "cses-building-roads",
          "cses-message-route",
          "cses-building-teams",
          "cses-round-trip",
          "cses-monsters",
          "cses-shortest-routes-i",
          "cses-flight-discount",
          "cses-cycle-finding",
          "cses-course-schedule",
          "cses-road-reparation",
          "cses-road-construction",
          "cses-giant-pizza",
        ],
      },
      {
        title: "CSES Range Queries",
        items: [
          "cses-static-range-sum-queries",
          "cses-static-range-minimum-queries",
          "cses-dynamic-range-sum-queries",
          "cses-dynamic-range-minimum-queries",
          "cses-range-xor-queries",
          "cses-forest-queries",
          "cses-hotel-queries",
          "cses-subarray-sum-queries",
        ],
      },
      {
        title: "CSES Tree Algorithms",
        items: [
          "cses-subordinates",
          "cses-tree-matching",
          "cses-tree-diameter",
          "cses-tree-distances-i",
          "cses-company-queries-i",
          "cses-distance-queries",
          "cses-subtree-queries",
          "cses-finding-a-centroid",
        ],
      },
      {
        title: "CSES Mathematics and String Algorithms",
        items: [
          "cses-josephus-queries",
          "cses-exponentiation",
          "cses-counting-divisors",
          "cses-common-divisors",
          "cses-word-combinations",
          "cses-string-matching",
          "cses-finding-borders",
          "cses-minimal-rotation",
        ],
      },
    ],
  },
  cses: [
    {
      category: "Introductory Problems",
      items: [
        { id: 1068, title: "Weird Algorithm" },
        { id: 1083, title: "Missing Number" },
        { id: 1069, title: "Repetitions" },
        { id: 1094, title: "Increasing Array" },
        { id: 1070, title: "Permutations" },
        { id: 1071, title: "Number Spiral" },
        { id: 1072, title: "Two Knights" },
        { id: 1092, title: "Two Sets" },
        { id: 1617, title: "Bit Strings" },
        { id: 1618, title: "Trailing Zeros" },
        { id: 1754, title: "Coin Piles" },
        { id: 1755, title: "Palindrome Reorder" },
        { id: 2205, title: "Gray Code" },
        { id: 2165, title: "Tower of Hanoi" },
        { id: 1622, title: "Creating Strings" },
        { id: 1623, title: "Apple Division" },
        { id: 1624, title: "Chessboard and Queens" },
        { id: 3399, title: "Raab Game I" },
        { id: 3419, title: "Mex Grid Construction" },
        { id: 3217, title: "Knight Moves Grid" },
        { id: 3311, title: "Grid Coloring I" },
        { id: 2431, title: "Digit Queries" },
        { id: 1743, title: "String Reorder" },
        { id: 1625, title: "Grid Path Description" },
      ],
    },
    {
      category: "Sorting and Searching",
      items: [
        { id: 1621, title: "Distinct Numbers" },
        { id: 1084, title: "Apartments" },
        { id: 1090, title: "Ferris Wheel" },
        { id: 1091, title: "Concert Tickets" },
        { id: 1619, title: "Restaurant Customers" },
        { id: 1629, title: "Movie Festival" },
        { id: 1640, title: "Sum of Two Values" },
        { id: 1643, title: "Maximum Subarray Sum" },
        { id: 1074, title: "Stick Lengths" },
        { id: 2183, title: "Missing Coin Sum" },
        { id: 2216, title: "Collecting Numbers" },
        { id: 2217, title: "Collecting Numbers II" },
        { id: 1141, title: "Playlist" },
        { id: 1073, title: "Towers" },
        { id: 1163, title: "Traffic Lights" },
        { id: 3420, title: "Distinct Values Subarrays" },
        { id: 3421, title: "Distinct Values Subsequences" },
        { id: 2162, title: "Josephus Problem I" },
        { id: 2163, title: "Josephus Problem II" },
        { id: 2168, title: "Nested Ranges Check" },
        { id: 2169, title: "Nested Ranges Count" },
        { id: 1164, title: "Room Allocation" },
        { id: 1620, title: "Factory Machines" },
        { id: 1630, title: "Tasks and Deadlines" },
        { id: 1631, title: "Reading Books" },
        { id: 1641, title: "Sum of Three Values" },
        { id: 1642, title: "Sum of Four Values" },
        { id: 1645, title: "Nearest Smaller Values" },
        { id: 1660, title: "Subarray Sums I" },
        { id: 1661, title: "Subarray Sums II" },
        { id: 1662, title: "Subarray Divisibility" },
        { id: 2428, title: "Distinct Values Subarrays II" },
        { id: 1085, title: "Array Division" },
        { id: 1632, title: "Movie Festival II" },
        { id: 1644, title: "Maximum Subarray Sum II" },
      ],
    },
    {
      category: "Dynamic Programming",
      items: [
        { id: 1633, title: "Dice Combinations" },
        { id: 1634, title: "Minimizing Coins" },
        { id: 1635, title: "Coin Combinations I" },
        { id: 1636, title: "Coin Combinations II" },
        { id: 1637, title: "Removing Digits" },
        { id: 1638, title: "Grid Paths I" },
        { id: 1158, title: "Book Shop" },
        { id: 1746, title: "Array Description" },
        { id: 2413, title: "Counting Towers" },
        { id: 1639, title: "Edit Distance" },
        { id: 3403, title: "Longest Common Subsequence" },
        { id: 1744, title: "Rectangle Cutting" },
        { id: 3359, title: "Minimal Grid Path" },
        { id: 1745, title: "Money Sums" },
        { id: 1097, title: "Removal Game" },
        { id: 1093, title: "Two Sets II" },
        { id: 3314, title: "Mountain Range" },
        { id: 1145, title: "Increasing Subsequence" },
        { id: 1140, title: "Projects" },
        { id: 1653, title: "Elevator Rides" },
        { id: 2181, title: "Counting Tilings" },
        { id: 2220, title: "Counting Numbers" },
        { id: 1748, title: "Increasing Subsequence II" },
      ],
    },
    {
      category: "Graph Algorithms",
      items: [
        { id: 1192, title: "Counting Rooms" },
        { id: 1193, title: "Labyrinth" },
        { id: 1666, title: "Building Roads" },
        { id: 1667, title: "Message Route" },
        { id: 1668, title: "Building Teams" },
        { id: 1669, title: "Round Trip" },
        { id: 1194, title: "Monsters" },
        { id: 1671, title: "Shortest Routes I" },
        { id: 1672, title: "Shortest Routes II" },
        { id: 1673, title: "High Score" },
        { id: 1195, title: "Flight Discount" },
        { id: 1197, title: "Cycle Finding" },
        { id: 1196, title: "Flight Routes" },
        { id: 1678, title: "Round Trip II" },
        { id: 1679, title: "Course Schedule" },
        { id: 1680, title: "Longest Flight Route" },
        { id: 1681, title: "Game Routes" },
        { id: 1202, title: "Investigation" },
        { id: 1750, title: "Planets Queries I" },
        { id: 1160, title: "Planets Queries II" },
        { id: 1751, title: "Planets Cycles" },
        { id: 1675, title: "Road Reparation" },
        { id: 1676, title: "Road Construction" },
        { id: 1682, title: "Flight Routes Check" },
        { id: 1683, title: "Planets and Kingdoms" },
        { id: 1684, title: "Giant Pizza" },
        { id: 1686, title: "Coin Collector" },
        { id: 1691, title: "Mail Delivery" },
        { id: 1692, title: "De Bruijn Sequence" },
        { id: 1693, title: "Teleporters Path" },
        { id: 1690, title: "Hamiltonian Flights" },
        { id: 1689, title: "Knight\u0027s Tour" },
        { id: 1694, title: "Download Speed" },
        { id: 1695, title: "Police Chase" },
        { id: 1696, title: "School Dance" },
        { id: 1711, title: "Distinct Routes" },
      ],
    },
    {
      category: "Range Queries",
      items: [
        { id: 1646, title: "Static Range Sum Queries" },
        { id: 1647, title: "Static Range Minimum Queries" },
        { id: 1648, title: "Dynamic Range Sum Queries" },
        { id: 1649, title: "Dynamic Range Minimum Queries" },
        { id: 1650, title: "Range Xor Queries" },
        { id: 1651, title: "Range Update Queries" },
        { id: 1652, title: "Forest Queries" },
        { id: 1143, title: "Hotel Queries" },
        { id: 1749, title: "List Removals" },
        { id: 1144, title: "Salary Queries" },
        { id: 2166, title: "Prefix Sum Queries" },
        { id: 2206, title: "Pizzeria Queries" },
        { id: 3304, title: "Visible Buildings Queries" },
        { id: 3163, title: "Range Interval Queries" },
        { id: 1190, title: "Subarray Sum Queries" },
        { id: 3226, title: "Subarray Sum Queries II" },
        { id: 1734, title: "Distinct Values Queries" },
        { id: 3356, title: "Distinct Values Queries II" },
        { id: 2416, title: "Increasing Array Queries" },
        { id: 1664, title: "Movie Festival Queries" },
        { id: 1739, title: "Forest Queries II" },
        { id: 1735, title: "Range Updates and Sums" },
        { id: 1736, title: "Polynomial Queries" },
        { id: 1737, title: "Range Queries and Copies" },
        { id: 2184, title: "Missing Coin Sum Queries" },
      ],
    },
    {
      category: "Tree Algorithms",
      items: [
        { id: 1674, title: "Subordinates" },
        { id: 1130, title: "Tree Matching" },
        { id: 1131, title: "Tree Diameter" },
        { id: 1132, title: "Tree Distances I" },
        { id: 1133, title: "Tree Distances II" },
        { id: 1687, title: "Company Queries I" },
        { id: 1688, title: "Company Queries II" },
        { id: 1135, title: "Distance Queries" },
        { id: 1136, title: "Counting Paths" },
        { id: 1137, title: "Subtree Queries" },
        { id: 1138, title: "Path Queries" },
        { id: 2134, title: "Path Queries II" },
        { id: 1139, title: "Distinct Colors" },
        { id: 2079, title: "Finding a Centroid" },
        { id: 2080, title: "Fixed-Length Paths I" },
        { id: 2081, title: "Fixed-Length Paths II" },
      ],
    },
    {
      category: "Mathematics",
      items: [
        { id: 2164, title: "Josephus Queries" },
        { id: 1095, title: "Exponentiation" },
        { id: 1712, title: "Exponentiation II" },
        { id: 1713, title: "Counting Divisors" },
        { id: 1081, title: "Common Divisors" },
        { id: 1082, title: "Sum of Divisors" },
        { id: 2182, title: "Divisor Analysis" },
        { id: 2185, title: "Prime Multiples" },
        { id: 2417, title: "Counting Coprime Pairs" },
        { id: 3396, title: "Next Prime" },
        { id: 1079, title: "Binomial Coefficients" },
        { id: 1715, title: "Creating Strings II" },
        { id: 1716, title: "Distributing Apples" },
        { id: 1717, title: "Christmas Party" },
        { id: 3397, title: "Permutation Order" },
        { id: 3398, title: "Permutation Rounds" },
        { id: 2064, title: "Bracket Sequences I" },
        { id: 2187, title: "Bracket Sequences II" },
        { id: 2209, title: "Counting Necklaces" },
        { id: 2210, title: "Counting Grids" },
        { id: 1722, title: "Fibonacci Numbers" },
        { id: 1096, title: "Throwing Dice" },
        { id: 1723, title: "Graph Paths I" },
        { id: 1724, title: "Graph Paths II" },
        { id: 3154, title: "System of Linear Equations" },
        { id: 3355, title: "Sum of Four Squares" },
        { id: 3406, title: "Triangle Number Sums" },
        { id: 1725, title: "Dice Probability" },
        { id: 1726, title: "Moving Robots" },
        { id: 1727, title: "Candy Lottery" },
        { id: 1728, title: "Inversion Probability" },
        { id: 1729, title: "Stick Game" },
        { id: 1730, title: "Nim Game I" },
        { id: 1098, title: "Nim Game II" },
        { id: 1099, title: "Stair Game" },
        { id: 2207, title: "Grundy\u0027s Game" },
        { id: 2208, title: "Another Game" },
      ],
    },
    {
      category: "String Algorithms",
      items: [
        { id: 1731, title: "Word Combinations" },
        { id: 1753, title: "String Matching" },
        { id: 1732, title: "Finding Borders" },
        { id: 1733, title: "Finding Periods" },
        { id: 1110, title: "Minimal Rotation" },
        { id: 1111, title: "Longest Palindrome" },
        { id: 3138, title: "All Palindromes" },
        { id: 1112, title: "Required Substring" },
        { id: 2420, title: "Palindrome Queries" },
        { id: 2102, title: "Finding Patterns" },
        { id: 2103, title: "Counting Patterns" },
        { id: 2104, title: "Pattern Positions" },
        { id: 2105, title: "Distinct Substrings" },
        { id: 1149, title: "Distinct Subsequences" },
        { id: 2106, title: "Repeating Substring" },
        { id: 2107, title: "String Functions" },
        { id: 3225, title: "Inverse Suffix Array" },
        { id: 1113, title: "String Transform" },
        { id: 2108, title: "Substring Order I" },
        { id: 2109, title: "Substring Order II" },
        { id: 2110, title: "Substring Distribution" },
      ],
    },
    {
      category: "Geometry",
      items: [
        { id: 2189, title: "Point Location Test" },
        { id: 2190, title: "Line Segment Intersection" },
        { id: 2191, title: "Polygon Area" },
        { id: 2192, title: "Point in Polygon" },
        { id: 2193, title: "Polygon Lattice Points" },
        { id: 2194, title: "Minimum Euclidean Distance" },
        { id: 2195, title: "Convex Hull" },
        { id: 3410, title: "Maximum Manhattan Distances" },
        { id: 3411, title: "All Manhattan Distances" },
        { id: 1740, title: "Intersection Points" },
        { id: 3427, title: "Line Segments Trace I" },
        { id: 3428, title: "Line Segments Trace II" },
        { id: 3429, title: "Lines and Queries I" },
        { id: 3430, title: "Lines and Queries II" },
        { id: 1741, title: "Area of Rectangles" },
        { id: 1742, title: "Robot Path" },
      ],
    },
    {
      category: "Advanced Techniques",
      items: [
        { id: 1628, title: "Meet in the Middle" },
        { id: 2136, title: "Hamming Distance" },
        { id: 3360, title: "Corner Subgrid Check" },
        { id: 2137, title: "Corner Subgrid Count" },
        { id: 2138, title: "Reachable Nodes" },
        { id: 2143, title: "Reachability Queries" },
        { id: 2072, title: "Cut and Paste" },
        { id: 2073, title: "Substring Reversals" },
        { id: 2074, title: "Reversals and Sums" },
        { id: 2076, title: "Necessary Roads" },
        { id: 2077, title: "Necessary Cities" },
        { id: 2078, title: "Eulerian Subgraphs" },
        { id: 2084, title: "Monster Game I" },
        { id: 2085, title: "Monster Game II" },
        { id: 2086, title: "Subarray Squares" },
        { id: 2087, title: "Houses and Schools" },
        { id: 2088, title: "Knuth Division" },
        { id: 2111, title: "Apples and Bananas" },
        { id: 2112, title: "One Bit Positions" },
        { id: 2113, title: "Signal Processing" },
        { id: 2101, title: "New Roads Queries" },
        { id: 2133, title: "Dynamic Connectivity" },
        { id: 2121, title: "Parcel Delivery" },
        { id: 2129, title: "Task Assignment" },
        { id: 2130, title: "Distinct Routes II" },
      ],
    },
    {
      category: "Sliding Window Problems",
      items: [
        { id: 3220, title: "Sliding Window Sum" },
        { id: 3221, title: "Sliding Window Minimum" },
        { id: 3426, title: "Sliding Window Xor" },
        { id: 3405, title: "Sliding Window Or" },
        { id: 3222, title: "Sliding Window Distinct Values" },
        { id: 3224, title: "Sliding Window Mode" },
        { id: 3219, title: "Sliding Window Mex" },
        { id: 1076, title: "Sliding Window Median" },
        { id: 1077, title: "Sliding Window Cost" },
        { id: 3223, title: "Sliding Window Inversions" },
        { id: 3227, title: "Sliding Window Advertisement" },
      ],
    },
    {
      category: "Interactive Problems",
      items: [
        { id: 3112, title: "Hidden Integer" },
        { id: 3139, title: "Hidden Permutation" },
        { id: 3305, title: "K-th Highest Score" },
        { id: 3228, title: "Permuted Binary Strings" },
        { id: 3273, title: "Colored Chairs" },
        { id: 3140, title: "Inversion Sorting" },
      ],
    },
    {
      category: "Bitwise Operations",
      items: [
        { id: 1146, title: "Counting Bits" },
        { id: 1655, title: "Maximum Xor Subarray" },
        { id: 3191, title: "Maximum Xor Subset" },
        { id: 3211, title: "Number of Subset Xors" },
        { id: 3192, title: "K Subset Xors" },
        { id: 3233, title: "All Subarray Xors" },
        { id: 2419, title: "Xor Pyramid Peak" },
        { id: 3194, title: "Xor Pyramid Diagonal" },
        { id: 3195, title: "Xor Pyramid Row" },
        { id: 1654, title: "SOS Bit Problem" },
        { id: 3141, title: "And Subset Count" },
      ],
    },
    {
      category: "Construction Problems",
      items: [
        { id: 2214, title: "Inverse Inversions" },
        { id: 2215, title: "Monotone Subsequences" },
        { id: 3422, title: "Third Permutation" },
        { id: 3423, title: "Permutation Prime Sums" },
        { id: 1697, title: "Chess Tournament" },
        { id: 3424, title: "Distinct Sums Grid" },
        { id: 2423, title: "Filling Trominos" },
        { id: 2418, title: "Grid Path Construction" },
      ],
    },
    {
      category: "Advanced Graph Problems",
      items: [
        { id: 3303, title: "Nearest Shops" },
        { id: 1134, title: "Prüfer Code" },
        { id: 1702, title: "Tree Traversals" },
        { id: 1757, title: "Course Schedule II" },
        { id: 1756, title: "Acyclic Graph Edges" },
        { id: 2177, title: "Strongly Connected Edges" },
        { id: 2179, title: "Even Outdegree Edges" },
        { id: 1707, title: "Graph Girth" },
        { id: 3357, title: "Fixed Length Walk Queries" },
        { id: 3111, title: "Transfer Speeds Sum" },
        { id: 3407, title: "MST Edge Check" },
        { id: 3408, title: "MST Edge Set Check" },
        { id: 3409, title: "MST Edge Cost" },
        { id: 1677, title: "Network Breakdown" },
        { id: 3114, title: "Tree Coin Collecting I" },
        { id: 3149, title: "Tree Coin Collecting II" },
        { id: 1700, title: "Tree Isomorphism I" },
        { id: 1701, title: "Tree Isomorphism II" },
        { id: 1699, title: "Flight Route Requests" },
        { id: 1703, title: "Critical Cities" },
        { id: 1203, title: "Visiting Cities" },
        { id: 3308, title: "Graph Coloring" },
        { id: 3158, title: "Bus Companies" },
        { id: 3358, title: "Split into Two Paths" },
        { id: 1704, title: "Network Renovation" },
        { id: 1705, title: "Forbidden Cities" },
        { id: 1752, title: "Creating Offices" },
        { id: 1685, title: "New Flight Routes" },
      ],
    },
    {
      category: "Counting Problems",
      items: [
        { id: 3413, title: "Filled Subgrid Count I" },
        { id: 3414, title: "Filled Subgrid Count II" },
        { id: 3415, title: "All Letter Subgrid Count I" },
        { id: 3416, title: "All Letter Subgrid Count II" },
        { id: 3417, title: "Border Subgrid Count I" },
        { id: 3418, title: "Border Subgrid Count II" },
        { id: 3400, title: "Raab Game II" },
        { id: 1080, title: "Empty String" },
        { id: 2229, title: "Permutation Inversions" },
        { id: 2176, title: "Counting Bishops" },
        { id: 2228, title: "Counting Sequences" },
        { id: 1078, title: "Grid Paths II" },
        { id: 1075, title: "Counting Permutations" },
        { id: 2429, title: "Grid Completion" },
        { id: 2421, title: "Counting Reorders" },
        { id: 3232, title: "Tournament Graph Distribution" },
        { id: 3157, title: "Collecting Numbers Distribution" },
        { id: 2415, title: "Functional Graph Distribution" },
      ],
    },
    {
      category: "Additional Problems I",
      items: [
        { id: 1087, title: "Shortest Subsequence" },
        { id: 3150, title: "Distinct Values Sum" },
        { id: 3190, title: "Distinct Values Splits" },
        { id: 1670, title: "Swap Game" },
        { id: 3175, title: "Beautiful Permutation II" },
        { id: 2422, title: "Multiplication Table" },
        { id: 3151, title: "Bubble Sort Rounds I" },
        { id: 3152, title: "Bubble Sort Rounds II" },
        { id: 3306, title: "Nearest Campsites I" },
        { id: 3307, title: "Nearest Campsites II" },
        { id: 1142, title: "Advertisement" },
        { id: 2186, title: "Special Substrings" },
        { id: 3169, title: "Counting LCM Arrays" },
        { id: 3193, title: "Square Subsets" },
        { id: 3294, title: "Subarray Sum Constraints" },
        { id: 3213, title: "Water Containers Moves" },
        { id: 3214, title: "Water Containers Queries" },
        { id: 2425, title: "Stack Weights" },
        { id: 3301, title: "Maximum Average Subarrays" },
        { id: 3302, title: "Subsets with Fixed Average" },
        { id: 3361, title: "Two Array Average" },
        { id: 1747, title: "Pyramid Array" },
        { id: 3404, title: "Permutation Subsequence" },
        { id: 1188, title: "Bit Inversions" },
        { id: 1086, title: "Writing Numbers" },
        { id: 2427, title: "Letter Pair Move Game" },
        { id: 1147, title: "Maximum Building I" },
        { id: 1162, title: "Sorting Methods" },
        { id: 1191, title: "Cyclic Array" },
        { id: 2414, title: "List of Sums" },
      ],
    },
    {
      category: "Additional Problems II",
      items: [
        { id: 3215, title: "Bouncing Ball Steps" },
        { id: 3216, title: "Bouncing Ball Cycle" },
        { id: 3218, title: "Knight Moves Queries" },
        { id: 3108, title: "K Subset Sums I" },
        { id: 3109, title: "K Subset Sums II" },
        { id: 2132, title: "Increasing Array II" },
        { id: 1189, title: "Food Division" },
        { id: 1698, title: "Swap Round Sorting" },
        { id: 2430, title: "Binary Subsequences" },
        { id: 1706, title: "School Excursion" },
        { id: 1709, title: "Coin Grid" },
        { id: 3312, title: "Grid Coloring II" },
        { id: 2426, title: "Programmers and Artists" },
        { id: 2174, title: "Removing Digits II" },
        { id: 2180, title: "Coin Arrangement" },
        { id: 3159, title: "Replace with Difference" },
        { id: 2432, title: "Grid Puzzle I" },
        { id: 2131, title: "Grid Puzzle II" },
        { id: 2115, title: "Bit Substrings" },
        { id: 2075, title: "Reversal Sorting" },
        { id: 1159, title: "Book Shop II" },
        { id: 3161, title: "GCD Subsets" },
        { id: 3402, title: "Minimum Cost Pairs" },
        { id: 3425, title: "Same Sum Subsets" },
        { id: 1157, title: "Mex Grid Queries" },
        { id: 1148, title: "Maximum Building II" },
        { id: 1161, title: "Stick Divisions" },
        { id: 3401, title: "Stick Difference" },
        { id: 1665, title: "Coding Company" },
        { id: 2402, title: "Two Stacks Sorting" },
      ],
    },
  ],
};
